### ISSUE TITLE
Requirements for job searching project?

### ISSUE THREAD

**Issue by PeterN00** [PeterN00/JobSearchProject#2]

**Comment by NguyenTienDat-1002** [comment]
we have employee, employer, employee-account, employer-account, post, CV in this website

**Comment by NguyenTienDat-1002** [comment]
employee cannot see posts in the past

**Comment by PeterN00** [comment]
Detail for each job post: position, level, salary, location, job description, job requirements.

**Comment by MinhKhoe** [comment]
user can search by date , title, position

**Comment by NguyenTienDat-1002** [comment]
a post have to be provided a logo of company

**Comment by NguyenTienDat-1002** [comment]
> user can search by date , title, position

all posts are available with employee so we don't need to search by date

**Comment by NguyenTienDat-1002** [comment]
> Detail for each job post: position, level, salary, location, job description, job requirements.

it should contain the industry for clarifying by industry
