### ISSUE TITLE
Missing laralvel/ui package

### ISSUE THREAD

**Issue by PeterN00** [PeterN00/JobSearchProject#4]
Got an error: "In order to use the Auth::routes() method, please install the laravel/ui package."

**Comment by NguyenTienDat-1002** [comment]
install
composer require laravel/ui
php artisan ui vue --auth
[https://codeinu.net/language/php/c616125-installed-laravel-ui-but-in-order-to-use-the-auth-routes-method-please-install-the-laravel-ui-package](url)
